### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IlievskiV** [wngu6/tourpy#1]
Hi,

I was wondering if this project under development, or if there are any other open-source libraries implementing the `tour` visualizations in Python?

**Comment by wngu6** [comment]
This is the only project that's implemented the tour algorithm in Python. Sorry, I haven't touched it in a while. I should start going back to it.

**Comment by IlievskiV** [comment]
Alright, thanks for letting me know. I am interested in `tour` visualizations. Do you mind if I give you a hand developing it?

**Comment by wngu6** [comment]
I don't mind.
